name: MLflow CI

on:
  push:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: heart_env

    - name: Install MLflow CLI
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        conda run -n heart_env mlflow run MLProject --entry-point main

    - name: Upload trained model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: MLProject/artifacts/model

    # # - name: Debug Docker Secrets_2
    # #   env:
    # #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    # #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    # #   run: |
    # #     echo "Username: ${DOCKER_USERNAME}"
    # #     echo "Password length: ${#DOCKER_PASSWORD}"

    # - name: Build and Push Docker image with MLflow
    #   run: |
    #     mlflow models build-docker -m MLProject/artifacts/model -n mlflow-heart-model
    #     docker tag mlflow-heart-model ${{ secrets.DOCKER_USERNAME }}/mlflow-heart-model:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-heart-model:latest
  
    - name: Debug Docker Secrets (optional)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Username: ${DOCKER_USERNAME}"
        echo "Password length: ${#DOCKER_PASSWORD}"

    - name: Build Docker image with MLflow
      run: |
        mlflow models build-docker -m MLProject/artifacts/model -n mlflow-heart-model
        docker tag mlflow-heart-model ${{ secrets.DOCKER_USERNAME }}/mlflow-heart-model:latest

    - name: Login to Docker Hub (update)
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/mlflow-heart-model:latest