name: MLflow CI

on:
  push:
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: MLProject/conda.yaml
        activate-environment: heart_env

    - name: Install MLflow CLI
      run: |
        pip install mlflow

    - name: Run MLflow Project
      run: |
        conda run -n heart_env mlflow run MLProject --entry-point main

    - name: Commit model artifacts to GitHub (Update_2)
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
        git add MLProject/artifacts/model || echo "No new artifacts to add"
        git commit -m "Add trained model artifact" || echo "No changes to commit"
        git push || echo "No changes to push"

